### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by zvukoper** [scottleedavis/mattermost-remind#114]
Tried to build it, but it failed. Can you tell whether it is all working or not? I mean, I see a badge BUILD:FAILING and I'm new here and I probably do not understand something.

I saw the announcement, that you switched to plugin development. Does that mean this version is not working and I'd better switch to plugin now?

Thank you.

**Comment by scottleedavis** [comment]
Hi @zvukoper,

This build should be working OK and has for another and for myself fairly recently.   I have not had the ability to contribute lately.  I do feel a plugin is the correct approach.

The current build failure is due to unit tests referring to the year 2018 instead of 2019.

**Comment by scottleedavis** [comment]
@zvukoper 

You are welcome to join the remind bot plugin channel on the community server to participate in building the plugin!

https://community.mattermost.com/core/channels/remindbot

**Comment by zvukoper** [comment]
@scottleedavis 
Thank you for your answers and the invitation.
