### ISSUE TITLE
Command with a trigger /remind not found

### ISSUE THREAD

**Issue by tungle** [scottleedavis/mattermost-remind#117]
Hi, suddenly I got this error "Command with a trigger /remind not found". What just happened? (I can still remind myself though, like "/remind me ...." )
![report](https://user-images.githubusercontent.com/1575905/58752579-6cd34480-84db-11e9-922f-a372cda248ce.png)

**Comment by scottleedavis** [comment]
Hi @tungle, strange indeed.
Does this work?
/remind @pha.nguyen "to report on forming hypo" on Thursday at 6pm.

**Comment by scottleedavis** [comment]
Try the plugin version!  https://github.com/scottleedavis/mattermost-plugin-remind

**Comment by tungle** [comment]
@scottleedavis thanks for your reply. What do you mean by "try the plugin version". Of course I'm using the plug-in (your plug-in), there's no native remind in mattermost

**Comment by tungle** [comment]
Ah got it, it's another repo. But yes, I'm using that plugin version, not this, my bad, wrong posting!

**Comment by scottleedavis** [comment]
Reposted to other repo.  The plugin is crashing on the syntax quick isn't correct but the plugin shouldn't crash.  Did the quotes approach example I shared work?
