### ISSUE TITLE
Can I add reminders to private channels?

### ISSUE THREAD

**Issue by molczyk** [scottleedavis/mattermost-remind#118]
Is there a way to add reminders to private channels? Of course I'm a member on this channel :)

**Comment by scottleedavis** [comment]
Yes @molczyk!

**Comment by scottleedavis** [comment]
Oh wait, I thought this repo was mattermost-plugin-remind, where you can.  This repo mattermost-remind you can't.  This repo is not maintained

**Comment by molczyk** [comment]
Oh ok. So then I will use the other one. Thanks for info.
