### ISSUE TITLE
every + multiple days results in multiple entries in the list

### ISSUE THREAD

**Issue by VincentSC** [scottleedavis/mattermost-remind#119]
When I do a "/remind ~town-square 'text' every monday and tuesday and wednesday and thursday and friday at 5pm" this results in multiple entries in the list. I'm pretty sure something goes wrong here.

**Comment by scottleedavis** [comment]
This was a prior big thought fixed.  Will look into this.

**Comment by scottleedavis** [comment]
Oh wait.  This repo is no longer supported.  Please use mattermost-plugin-remind instead.

**Comment by VincentSC** [comment]
Oops, put it in the wrong repo indeed.
