### ISSUE TITLE
@ calls are not notifying people that have them set up

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-remind#98]
Submitter: Cissie
I have @formdev set to notify me every time a message is posted using it, however when it's added via the remind bot I'm not notified.

The following 2 reminders were posted via the remind bot in the CollegeNET #webdev_forms channel this morning while I was logged in and I wasn't pinged and others who have notifications setup for the @formdev call were also not pinged:
You asked me to remind you "@formdev [ Ticket : 342E5CB80A0249BC ] go live with edit 07.31".
You asked me to remind you "@formdev [ Ticket : E2797CAE5C7BA88A ] go live with edit 07.31".

Thanks!

**Comment by scottleedavis** [comment]
set it up as a trigger word for our own notifications,

**Comment by scottleedavis** [comment]
https://forum.mattermost.org/t/response-attachments-text-do-not-trigger-word-notifications/5484

**Comment by scottleedavis** [comment]
Awaiting mattermost version 5.2

**Comment by arjitc** [comment]
Hey @scottleedavis Mattermost 5.2 is out now, would be awesome to have this feature 👍

**Comment by scottleedavis** [comment]
alll done!
